### ISSUE TITLE
ARM_BEETLE_SOC: IAR export failure

### ISSUE THREAD

**Issue by sunsmilearm** [ARMmbed/oob-mbed-os-example-ble#13]
Command:
mbed export -i iar -m ARM_BEETLE_SOC

error message:

```
Traceback (most recent call last):
  File "C:\my\dev\mbed_5_0\oob_520\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project.py", line 234, in <module>
    main()
  File "C:\my\dev\mbed_5_0\oob_520\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project.py", line 230, in main
    zip_proj=zip_proj, build_profile=profile)
  File "C:\my\dev\mbed_5_0\oob_520\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project.py", line 93, in export
    build_profile=build_profile, silent=silent)
  File "C:\my\dev\mbed_5_0\oob_520\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project_api.py", line 229, in export_project
    macros=macros)
  File "C:\my\dev\mbed_5_0\oob_520\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project_api.py", line 89, in generate_project_files
    exporter.check_supported()
  File "C:\my\dev\mbed_5_0\oob_520\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\export\exporters.py", line 126, in check_supported
    raise TargetNotSupportedException()
tools.export.exporters.TargetNotSupportedException
[mbed] ERROR: "python" returned error code 1.
[mbed] ERROR: Command "python -u C:\my\dev\mbed_5_0\oob_520\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project.py -i iar -m ARM_BEETLE_SOC --source ." in "C:\my\dev\mbed_5
_0\oob_520\oob-mbed-os-example-ble\BLE_HeartRate"
```

It seems target is not supported.

**Comment by pan-** [comment]
@0xc0170 Exporters ?

**Comment by MarceloSalazar** [comment]
No official pack for this platform so this cannot be fixed for RC3. This will need to be treated like the other 5.0 targets which don’t support exporters. These configurations should be excluded for OOB testing.
