### ISSUE TITLE
nRF52_DK : Export to uVision5, target not supported.

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/oob-mbed-os-example-ble#4]
Steps to reproduce:
$> mbed export -i uvision5 -m nrf52_dk

(snip)

Scan: FEATURE_THREAD_ROUTER
Scan: FEATURE_STORAGE
Traceback (most recent call last):
  File "C:\Ashok\mbed_CLI\nRF52_OOB_example\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project.py", line 234, in <module>
    main()
  File "C:\Ashok\mbed_CLI\nRF52_OOB_example\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project.py", line 230, in main
    zip_proj=zip_proj, build_profile=profile)
  File "C:\Ashok\mbed_CLI\nRF52_OOB_example\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project.py", line 93, in export
    build_profile=build_profile, silent=silent)
  File "C:\Ashok\mbed_CLI\nRF52_OOB_example\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project_api.py", line 228, in export_project
    macros=macros)
  File "C:\Ashok\mbed_CLI\nRF52_OOB_example\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project_api.py", line 89, in generate_project_files
    exporter.generate()
  File "C:\Ashok\mbed_CLI\nRF52_OOB_example\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\export\uvision5.py", line 59, in generate
    project_data = self.progen_get_project_data()
  File "C:\Ashok\mbed_CLI\nRF52_OOB_example\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\export\exporters.py", line 122, in progen_get_project_data
    raise TargetNotSupportedException("Target not supported")
tools.export.exporters.TargetNotSupportedException: Target not supported
[mbed] ERROR: "python" returned error code 1.
[mbed] ERROR: Command "python -u C:\Ashok\mbed_CLI\nRF52_OOB_example\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project.py -i uvision5 -m nrf52_dk --source ." in "C:\Ashok\mbed_CLI\nRF52_OOB_example\oob-mbed-os-example-ble\BLE_HeartRate"

**Comment by ashok-rao** [comment]
Issue fixed in RC2. Closing. Thank you.
