### ISSUE TITLE
nRF52_DK : Export to IAR, target not supported

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/oob-mbed-os-example-ble#5]
Steps to reproduce:
$> mbed export -i iar -m nrf52_dk

(snip)

    exporter.generate()
  File "C:\Ashok\mbed_CLI\nRF52_OOB_example\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\export\iar.py", line 55, in generate
    project_data = self.progen_get_project_data()
  File "C:\Ashok\mbed_CLI\nRF52_OOB_example\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\export\exporters.py", line 122, in progen_get_project_data
    raise TargetNotSupportedException("Target not supported")
tools.export.exporters.TargetNotSupportedException: Target not supported
[mbed] ERROR: "python" returned error code 1.
[mbed] ERROR: Command "python -u C:\Ashok\mbed_CLI\nRF52_OOB_example\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project.py -i iar -m nrf52_dk --source ." in "C:\Ashok\mbed_CLI\nRF52_OOB_example\oob-mbed-os-example-ble\BLE_HeartRate"

**Comment by ashok-rao** [comment]
RC2, Issue still persists. Build log below:

C:\Ashok\mbed_CLI\OoB_round2\BLE\nrf52_dk\oob-mbed-os-example-ble\BLE_HeartRate>mbed export -i iar -m nrf52_dk

(snip)

Scan: FEATURE_STORAGE
Traceback (most recent call last):
  File "C:\Ashok\mbed_CLI\OoB_round2\BLE\nrf52_dk\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project.py", line 234, in <module>
    main()
  File "C:\Ashok\mbed_CLI\OoB_round2\BLE\nrf52_dk\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project.py", line 230, in main
    zip_proj=zip_proj, build_profile=profile)
  File "C:\Ashok\mbed_CLI\OoB_round2\BLE\nrf52_dk\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project.py", line 93, in export
    build_profile=build_profile, silent=silent)
  File "C:\Ashok\mbed_CLI\OoB_round2\BLE\nrf52_dk\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project_api.py", line 229, in export_project
    macros=macros)
  File "C:\Ashok\mbed_CLI\OoB_round2\BLE\nrf52_dk\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project_api.py", line 89, in generate_project_files
    exporter.check_supported()
  File "C:\Ashok\mbed_CLI\OoB_round2\BLE\nrf52_dk\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\export\exporters.py", line 126, in check_supported
    raise TargetNotSupportedException()
tools.export.exporters.TargetNotSupportedException
[mbed] ERROR: "python" returned error code 1.
[mbed] ERROR: Command "python -u C:\Ashok\mbed_CLI\OoB_round2\BLE\nrf52_dk\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project.py -i iar -m nrf52_dk --source ." in "C:\Ashok\mbed_CLI\OoB_round2\BLE\nrf52_dk\oob-mbed-os-example-ble\BLE_HeartRate"

**Comment by sarahmarshy** [comment]
Can you try with this PR: https://github.com/ARMmbed/mbed-os/issues/2985?

**Comment by ashok-rao** [comment]
@sarahmarshy , thanks. That PR works for the target support. Also, simulator is selected by default for the debug options. Doesn't this have to be CMSIS-DAP?

@0xc0170 , IAR now produces a build error similar to https://github.com/ARMmbed/oob-mbed-os-example-ble/issues/6 ..

![nrf52_iar_build_error](https://cloud.githubusercontent.com/assets/17567812/19306835/6edf4656-906f-11e6-9852-40bc5f583c6c.jpg)

**Comment by MarceloSalazar** [comment]
I assume the PR fixes this - could you confirm when testing RC3?
